config/routes.rb
Rails.application.routes.draw do
  resources :orgs
  get 'orgs/new'

  get 'orgs/create'

  get 'orgs/show'

  get 'orgs/add_group_to_user'

  get 'orgs/delete_group_from_user'

  get 'orgs/destroy'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'users/new'

  get 'users/create'

  root 'users#new'

  get '/signup' => 'users#new'
  post '/users' => 'users#create' 
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/dashboard' => 'orgs#dashboard'

  post '/create_group' => 'orgs#create'

  post '/join_org' => 'orgs#join_org'
  post '/drop_org' => 'orgs#drop_org'

  match "*path", to: "users#not_found", via: :all

end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :org
end

app/models/org.rb
class Org < ActiveRecord::Base
	has_many :memberships
	has_many :users, through: :memberships
	validates :name, :description, presence: true, length: {in:5..500}

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :memberships
	has_many :orgs, through: :memberships
	validates :email, presence: true, uniqueness: true, length: {in:5..50}
	validates :first_name, :last_name, :password, :password_confirmation, presence: true, length: {in:5..50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/orgs_controller.rb
class OrgsController < ApplicationController
  before_filter :authorize
  def new
  end

  def create
    @org = Org.new(org_params)
    @org.owner_id = current_user.id
    if @org.save
        redirect_to '/dashboard'
    else
      @orgs = Org.all
      render 'orgs/dashboard'
    end

    # if @org.save

    # render plain:  org_params
  end

  def show
    # render plain: params
    @org = Org.find_by_id(params[:id])

  end

  def add_group_to_user
  end

  def delete_group_from_user
  end

  def destroy
    @org = Org.find_by_id(params[:id])
    org_name = @org.name
    @org.destroy
    flash[:message] = "#{org_name} was deleted"
    redirect_to '/dashboard'
  end

  def dashboard
    # render plain: 'In Orgs dashboard'
    @orgs = Org.all
    @org = Org.new
  end

  def join_org
    # render plain: params
    @org = Org.find_by_id(params[:org_id])
    @org.users << current_user
    redirect_to '/dashboard'
  end

  def drop_org
    @org = Org.find_by_id(params[:org_id])
    @org.users.delete(current_user)
    redirect_to '/dashboard'
  end




  private
    def org_params
      params.require(:org).permit(:name, :description)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user 
      # logged in when they navigate around our website.
      session[:user_id] = user.id

      redirect_to '/dashboard'
    else
    # If user's login doesn't work, send them back to the login form.
      flash[:alert] ='Login failed. Check your Email and Password.'
      redirect_to '/signup'
    end
  end

  def destroy
  	flash[:nav] =' You have been successfully logged out.'
    session[:user_id] = nil
    redirect_to '/signup'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	# Remember to add before_filter :authorize to any controllers that 
	# should be blocked without proper login
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:alert] = "User #{@user.first_name} #{@user.last_name} created."
      redirect_to '/dashboard'
      # render plain: ' In saved'

    else

      render 'users/new'
    end
  end



  # holding page to be replaced by real page eventually.
  def holding_page

  end
  # for all unfoundpages that require 404
  def not_found
  end
  private
  	def user_params
  		params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orgs_helper.rb
module OrgsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Logintemplate</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if flash[:nav] %>
		<div style ='color:red;margin-left:20px;'><%=flash[:nav] %></div>
	<% end %>
<div class='header col-md-4 pull-right'>
	<% if current_user %>
	  Signed in as <%= current_user.first_name %> <%= current_user.last_name %>| <%= link_to "Logout", '/logout' %>
	<% else %>
	  <%= link_to 'Login', '/signup' %> | <%= link_to 'Signup', '/signup' %>
	<% end %>
</div>

<div id="main-container" class="container">
  <div class="row">

    <div class="col-sm-12">
      <%= yield %>
    </div>
  </div>
</div>

</body>
</html>

app/views/orgs/add_group_to_user.html.erb
<h1>Orgs#add_group_to_user</h1>
<p>Find me in app/views/orgs/add_group_to_user.html.erb</p>

app/views/orgs/create.html.erb
<h1>Orgs#create</h1>
<p>Find me in app/views/orgs/create.html.erb</p>

app/views/orgs/dashboard.html.erb
<div class ='col-sm-10'>
	<h3>Welcome <%=current_user.first_name %> <%=current_user.last_name %></h3> <br> <br>
	<%= flash[:message] if flash[:message] %>


		<div class = 'col-sm-6'>
				<h4>Here are the organizations you can join</h4>
			<% @orgs.each do |t| %>
			
				<%= link_to t.name, org_path(t) %> <% if t.owner_id == current_user.id %>
														- <%= link_to('Delete', org_path(t), :method => 'delete')%>
													<% end %> <br>
				
					Members: <%= Membership.where(org_id: t.id).count%><br> <br>
				&nbsp	<%=t.description%> <br>
					------------------ <br>
			<% end %>
		</div>

		<div class = 'col-md-4' style ='border:solid black .5px;padding-bottom:10px'>
			<%= bootstrap_form_for(@org, url: '/create_group') do |t| %>
				<%= t.text_field :name, placeholder: 'Group Name' %>
				<%= t.text_field :description, placeholder: 'Group description' %>
				<%= t.submit 'Create Org', class: 'btn btn-primary pull-right' %>
			<%end%>
		</div>





	


</div>

app/views/orgs/delete_group_from_user.html.erb
<h1>Orgs#delete_group_from_user</h1>
<p>Find me in app/views/orgs/delete_group_from_user.html.erb</p>

app/views/orgs/destroy.html.erb
<h1>Orgs#destroy</h1>
<p>Find me in app/views/orgs/destroy.html.erb</p>

app/views/orgs/new.html.erb
<h1>Orgs#new</h1>
<p>Find me in app/views/orgs/new.html.erb</p>

app/views/orgs/show.html.erb
<br><br><br>
<div class = 'row'>
	<div class = 'col-sm-3'>
		<%= @org.name %> <br> <br>
		<%=@org.description %> <br><br>
		<h4>Created By: <% if @org.owner_id == current_user.id %>
								YOU!	
						<%else %>
							<%= User.find_by_id(@org.owner_id).first_name %> <%=  User.find_by_id(@org.owner_id).last_name %>
						<%end%> </h4> <br>
		<h5>Members:</h5>
		<% @org.users.each do  |t| %>
			<%= t.first_name %> <%= t.last_name %> <br>
		<% end %>

	</div>
	<div class = 'col-sm-2'> 
	<% if @org.users.find_by_id(current_user.id)%>
	 		<%=button_to 'Leave Group', '/drop_org', :class => 'btn btn-danger pull-right',params: { org_id: @org.id } %> <br> <br>
	 	<% else %>
	 		<%= button_to 'Join Group', '/join_org', :class => 'btn btn-success pull-right',params: { org_id: @org.id } %><br><br>
	 	<% end %>
		
	</div>



</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/holding_page.html.erb
<h1>holding page</h1>
 <% if flash[:message] %>
	<h1 class = "btn-danger"><%= flash[:message] %></h1>
<% end %>



<%= link_to 'New User/Login', '/signup' %>

app/views/users/new.html.erb
<div class = 'row'>

	<div class = 'form col-md-5'>
			<h1>Signup!</h1>

		<%= bootstrap_form_for(@user, url: '/users') do |f| %>

			  <%= f.text_field :first_name %>
			  <%= f.text_field :last_name %>
			  <%= f.text_field :email %>
			  <%= f.password_field :password %>
			  <%= f.password_field :password_confirmation, label:'Retype Password'%>
			  <%= f.submit "Submit", class: 'btn btn-primary' %>

		<% end %>

	</div>

	<div class ='col-md-5'>
		<h1>Login</h1>
		<% if flash[:alert] %>
			<div style='color:red;'>
				<%= flash[:alert] %>
			</div>

		<% end %>
		<%= bootstrap_form_tag url: '/login' do |t|%>

		  <%= t.text_field :email, placeholder: "myname@mydomain.com" %>
		  <%= t.password_field :password, placeholder: "********" %>
		  <%= t.submit "Submit", class: 'btn btn-primary pull-right ' %>

		<% end %>
	</div>
</div>

app/views/users/not_found.html.erb
<h1> 404 Sorry, that page doesn't seem to exist</h1>